client/components/index.js
client/components/main.js
client/components/on-the-hunt.js
client/routes.js
package.json
public/index.html
server/db/db.js

(npm install then...) 
You will see your current latitude and longitude displayed in the browser, but not on the screen. 
---

accessing latitude and longitude in console, delayed on screen render

---

package-lock.json

moved secrets and serviceAccountKey.json

---

server/db/models/index.js
server/db/models/mission.js
server/db/models/team.js
server/db/models/user.js

Created user, team, mission models and associations

---

client/components/auth-form.js
client/store/user.js
script/seed.js
server/api/teams.js
server/api/users.js
server/db/models/index.js
server/db/models/user.js
server/db/models/user.spec.js

---
Please double-check syntax and logic for the teams and users api routes. More testing to come soon!

Creating api routes

---

script/seed.js
server/db/models/index.js
server/db/models/message.js
server/db/models/userTeamClueStatus.js

- join table with status column for user-team-clues
- updated team missions
- associated to a user and a team
- contains text which can't be null

monster join created!

---

server/api/messages.js
server/api/missions.js

**Messages**
-GET route for all messages by teamID
-POST route for new message
**Missions**
-GET all missions
-GET mission by ID

Added api routes for messages and missions

---

server/api/index.js
server/api/teams.js
server/isMemberOfTeam.js

- imported team router into api/index
- added User Model to Team router because it was crashing the server
- wrote middleware for rejecting non team members
:unicorn::unicorn::unicorn::unicorn::unicorn::unicorn:

37 is team member

---

script/seed.js
server/db/models/clue.js

---
Double check syntax and logic, please!

Creating seed file

---

package-lock.json
script/seed.js
server/db/models/clue.js
server/db/models/message.js
server/db/models/userTeamClueStatus.js

---
I assigned all UserTeamClueStatus data to team 1 as 'unassigned'. Each status is assigned to a different clue (1-4).

Debugging seed

---

script/seed.js
server/api/messages.js
server/api/teams.js

Routes we've tested:
- messages
- missions
- teams
- users
To be tested:
- push (subscriptions)
- clues

changes to seed file

---

public/sw.js
server/index.js
server/messageSubscribers.js

closes #73 
tested/corrected assignment logic,
updated object sent out so that message displays

Clue Renders in Notification on front end

---

server/api/clues.js
server/isMemberOfTeam.js

Fixes team member bug

---

client/index.js
client/store/user.js

no more landing page hiccup

---

script/seed.js
server/db/models/team.js
server/messageSubscribers.js

Mission completed, Sends out congrats, clears out extra clues, sets team to inactive until they sign up for a new mission

---

server/db/models/team.js
server/messageSubscribers.js

Review this last! Streak is now updated, users can loose streak, and their clues are added back to the pool

---

client/components/index.js
client/components/solve-clue.js
client/routes.js
server/api/clues.js

-Created single clue component
-Pulls in PhotoInput component
-Displays user's current clue (if on a team - otherwise it prompts user to select a team)
-Shows hints with each button click until hints run out

Single clue component

---

client/components/auth-form.js

Gallery view

---

package-lock.json
package.json

added modules to packagejson

---

client/components/gallery-view.js
client/components/main.js
client/components/photo-input.js
client/components/solve-clue.js
client/components/team-home.js
client/components/user-home.js
client/store/clues.js
client/store/index.js
client/store/photos.js
script/seed.js
server/api/clues.js
server/db/models/user.js

Home clues

---

client/components/auth-form.js
server/auth/index.js

Jazzed up auth form

---

client/components/bottom-nav.js
client/components/index.js
client/components/main.js
client/components/on-the-hunt.js
client/components/team-home.js
client/components/team-select.js
client/components/team.js
client/components/user-home.js

Teams menu

---

client/components/gallery-view.js
client/components/photo-input.js
server/api/clues.js

- edited photo verification responses
- edited the category headers in the gallery
- removed "team home" button from photo input page

changed clue verification responses and headers on gallery page

---

client/components/AddTeamMember.js
client/store/teamMembers.js
server/api/teams.js

fixed errors with add team member bugs

---

client/components/bottom-nav.js
client/components/user-home.js
public/index.html
public/style.css

adding background gradient and font-color

---

client/components/bottom-nav.js
client/components/main.js
client/components/messages.js
client/components/photo-input.js
client/components/user-home.js
public/index.html
public/style.css

Styling team navbar

---

client/components/main.js
client/components/on-the-hunt.js
client/store/user.js

- resolved 500 internal server error (fetchTeams() )
- commented out setCurrentLocation in on-the-hunt.js

resolved current errors

---

server/api/teams.js

fixed tiny bug

---

client/components/auth-form.js

fixed username bug

---

client/components/photo-input.js
client/components/solve-clue.js

- also solve-clue no longer extends component

solving clue updates team home

---

client/components/photo-input.js
script/seed.js

- photo verification happens before clue status is updated
- seed file updated

fixed a few bugs

---

client/components/team.js
client/store/clues.js
public/manifest.json
server/api/teams.js

fixed some bugs

---

client/components/bottom-nav.js
client/components/team.js
client/components/user-home.js
package.json
public/style.css

fixing navbar styling

---

client/components/photo-input.js
package-lock.json
script/seed.js
server/timer.js

fixed image verification
timer set to 24 hour interval
seed file updated

screencast version

---

client/components/bottom-nav.js
package-lock.json
public/style.css

changed divs to buttons and removed button styling

---

client/components/bottom-nav.js

fixed button clicks
